# Generated by Django 5.0.6 on 2024-06-10 12:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image_url', models.ImageField(upload_to=app.models.upload_to)),
            ],
        ),
    ]
